services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    restart: unless-stopped
    hostname: changedetection
    volumes:
      - data:/datastore
    ports:
      - 5000:5000

volumes:
  data:
