---
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: homelab
    environment:
      - PUID=${UUID:-1000}
      - PGID=${GUID:-1000}
      # Listen to 127.0.0.1 instead of 0.0.0.0
      - STGUIADDRESS=
    volumes:
      # Can be set in an .env file
      - ${HOST_MOUNT}:/var/syncthing
    # Use network host and no docker networks or abstractions
    network_mode: host
    # This is left for reference
    # ports:
    #   - 8384:8384 # Web UI
    #   - 22000:22000/tcp # TCP file transfers
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
